[package]
name = "coco"
version = "0.1.0"
authors = ["Alexander Simmerl <a.simmerl@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3", features = [ "compat" ] }
kv = { version = "0.20", features = [ "bincode-value", "json-value" ] }
lazy_static = "1.4"
log = "0.4"
nonempty = "0.5"
serde = { version = "1.0", features = [ "derive" ] }
syntect = "4.2"
thiserror = "1.0"
tokio = { version = "0.2", features = [ "dns", "macros", "time" ] }

[dependencies.librad]
git = "https://github.com/radicle-dev/radicle-link.git"
rev = "577e9943fa704895b47fe4e1c862bf0bd51d58a9"

[dependencies.radicle-git-helpers]
git = "https://github.com/radicle-dev/radicle-link.git"
rev = "577e9943fa704895b47fe4e1c862bf0bd51d58a9"

[dependencies.radicle-surf]
version = "0.4.1"
features = ["serialize"]

[dev-dependencies]
pretty_assertions = "0.6"
tempfile = "3.1"
