[package]
name = "proxy"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["radicle team <dev@radicle.xyz>"]
edition = "2018"
description = "Proxy to serve a specialised API to the Upstream UI."
readme = "https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/README.md"
categories = [ "crypto", "p2p" ]
keywords = [ "radicle-upstream", "proxy" ]
repository = "git@github.com:radicle-dev/radicle-upstream.git"

[dependencies]
async-trait = "0.1"
directories = "2.0"
futures = { version = "0.3", features = [ "compat" ] }
hex = "0.4"
kv = { version = "0.20", features = [ "bincode-value" ] }
log = "0.4"
nonempty = "0.2"
pico-args = "0.3"
pretty_env_logger = "0.3"
rand = "0.7"
serde = "1.0"
serde_cbor = "0.11.1"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.1"
tokio = { version = "0.2", features = [ "macros" ] }
url17 = { package = "url", version = "1.7" }
url = "2.1"
warp = { git = "https://github.com/radicle-dev/warp", branch = "openapi", features = [ "openapi" ] }

[dependencies.librad]
git = "https://github.com/radicle-dev/radicle-link.git"
rev = "4cedafaeb46deee4ec11d0e4b779a1a0d124d599"

[dependencies.radicle-registry-client]
git = "https://github.com/radicle-dev/radicle-registry.git"
rev = "f05517c470e426d2f59c9f873845b5e1019b57b4"

[dev-dependencies]
pretty_assertions = "0.6"
