[package]
name = "proxy"
version = "0.1.0"
license = "GPL"
authors = ["Alexander Simmerl <xla@monadic.xyz>"]
edition = "2018"
description = "Proxy to serve a specialised GraphQL API to radicle-upstream."
readme = "https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/README.md"
categories = [ "crypto", "p2p" ]
keywords = [ "radicle-upstream", "proxy" ]
repository = "git@github.com:radicle-dev/radicle-upstream.git"

[dependencies]
futures = "0.1"
hex = "0.4"
juniper = "0.14"
juniper_codegen = "0.14"
juniper_warp = "0.5"
log = "0.4"
pretty_env_logger = "0.3"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
warp = "0.1"

[dependencies.radicle_registry_client]
git = "https://github.com/radicle-dev/radicle-registry.git"
rev = "58e3b8bc79e556053d8e17dc21f72c8bbdf243e5"

[dependencies.radicle_registry_runtime]
git = "https://github.com/radicle-dev/radicle-registry.git"
rev = "58e3b8bc79e556053d8e17dc21f72c8bbdf243e5"

[dependencies.radicle-surf]
git = "https://github.com/radicle-dev/radicle-surf.git"
rev = "3ddc170c109b10273ea04659eb64ec6918189f70"

[dev-dependencies]
indexmap = "1.3"
pretty_assertions = "0.6"
