[package]
name = "proxy"
version = "0.1.0"
license = "GPL"
authors = ["Alexander Simmerl <xla@monadic.xyz>"]
edition = "2018"
description = "Proxy to serve a specialised GraphQL API to radicle-upstream."
readme = "https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/README.md"
categories = [ "crypto", "p2p" ]
keywords = [ "radicle-upstream", "proxy" ]
repository = "git@github.com:radicle-dev/radicle-upstream.git"

[dependencies]
futures = { version = "0.3", features = [ "compat" ] }
hex = "0.4"
juniper = "0.14"
juniper_codegen = "0.14"
juniper_warp = "0.5"
log = "0.4"
nonempty = "0.2"
pico-args = "0.3"
pretty_env_logger = "0.3"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.1"
url17 = { package = "url", version = "1.7" }
url = "2.1"
warp = "0.1"

[dependencies.librad]
git = "https://github.com/radicle-dev/radicle-link.git"
rev = "0034bd0fca27596b6fd2982ec875daa426ded120"

[dependencies.radicle-registry-client]
git = "https://github.com/radicle-dev/radicle-registry.git"
rev = "8689536f7e30d5e4839141658d2357e2cc550755"

[dependencies.radicle-surf]
version = "0.2"

[dev-dependencies]
indexmap = "1.3"
pretty_assertions = "0.6"
